version: "3.9"

services:
  whatsapp-app:
    build: .
    dockerfile: Dockerfile
    container_name: whatsapp-agent
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    volumes:
      - ./sessions:/app/.wwebjs_auth   # â¬… Persistencia segura del WhatsApp
      - ./logs:/app/logs
